#ifndef TOKENS_HPP
#define TOKENS_HPP

enum token_type {
  LEFT_PAREN, RIGHT_PAREN, LEFT_BRACE, RIGHT_BRACE, SEMICOLON, COLON,

  DOT, ARROW, ADD, ADD_EQUAL, SUBTRACT, SUBTRACT_EQUAL, EQUAL, EQUAL_EQUAL, GREATER, GREATER_EQUAL, LESS, LESS_EQUAL,

  IDENTIFIER, STRING_LITERAL,

  FUNC, VOID,

  END,

  UNKNOWN
};

#endif